Num1=int(input("Please Enter Number1 : "))
Num2=int(input("Please Enter Number2 : "))
print(Num1,"+",Num2,"=",Num1+Num2)
print(Num1,"-",Num2,"=",Num1-Num2)
print(Num1,"*",Num2,"=",Num1*Num2)
print(Num1,"/",Num2,"=",Num1/Num2)
